### ISSUE TITLE
I couldn't compile the source code

### ISSUE THREAD

**Issue by ayyucedemirbas** [zodiacon/DriverMon#1]
I received 65 error messages. Could you please help me?

![screenshot 123](https://user-images.githubusercontent.com/8023150/32418737-39b2c446-c280-11e7-8e22-362f44c94069.png)

**Comment by zodiacon** [comment]
First, you have to install the latest Windows Driver Kit

**Comment by ayyucedemirbas** [comment]
Thank you so much! I will try it after my computer science exam.
