### ISSUE TITLE
Failed to start driver. Exiting

### ISSUE THREAD

**Issue by asgarciap** [zodiacon/DriverMon#11]
I get this error when trying to run the last released version. Does DriverMon generates any logs where I can check why this could happen?
![image](https://user-images.githubusercontent.com/5125146/82110335-27ffe800-9703-11ea-89ca-425cdd749f76.png)

**Comment by zodiacon** [comment]
Make sure you are in test signing mode. Open an elevated command window:
bcdedit /set testsigning on
and restart the system

**Comment by asgarciap** [comment]
Thanks!
