### ISSUE TITLE
One more BSOD on monitoring NTFS driver

### ISSUE THREAD

**Issue by EthanZBY** [zodiacon/DriverMon#12]
Hi Pavel,

Please see the crash dump result screen shot.

I will keep the dump file for the moment If any further check on the dump file needed, just let me know.

![image](https://user-images.githubusercontent.com/41062494/95958249-74c32880-0e33-11eb-952b-c9042c93b865.png)

Regards,
Ethan

**Comment by zodiacon** [comment]
You can't monitor the NTFS driver with this technique on Windows 8+ because it's protected by PatchGuard.

**Comment by zodiacon** [comment]
I'll take a look anyway

**Comment by EthanZBY** [comment]
Thanks again.
