### ISSUE TITLE
SfDataGrid Compile error

### ISSUE THREAD

**Issue by ithurricane** [zodiacon/DriverMon#2]
The code won't compile with this error:
\DriverMon\DriverMon\Resources\Styles.xaml(11,73): error MC3066: 'SfDataGrid'
\DriverMon\DriverMon\Views\MainView.xaml(48,10): error MC3074: 'SfDataGrid'

where can i get <sf:SfDataGrid>?

**Comment by zodiacon** [comment]
This is part of Syncfusion WPF suite - you can download a free for non-profit version from their site. You can also try taking the DLL from one of the releases and place it in the project and output directory
