### ISSUE TITLE
CLR20r3 error when launching application

### ISSUE THREAD

**Issue by muniv11111** [zodiacon/DriverMon#3]
Microsoft Windows 7 Ultimate x86

app cannot by started - failed to load driver:

DriverMon-0.2-alpha: 

	EventType clr20r3
  P 01:	DriverMon.exe
  P 02:	1.0.0.0
  P 03:	59ff3a57
  P 04:	DriverMon
  P 05:	1.0.0.0
  P 06:	59ff3a57
  P 07:	8
  P 08:	67
  P 09:	System.ComponentModel.Win32
  OS version:	6.1.7601.2.1.0.256.1

  next info 1:	0a9e
  next info 2:	0a9e372d3b4ad19135b953a78882e789
  next info 3:	0a9e
  next info 4:	0a9e372d3b4ad19135b953a78882e789

DriverMon-0.3-beta: 

EventType clr20r3
  P 01:	DriverMon.exe
  P 02:	1.0.0.0
  P 03:	5a0c2db1
  P 04:	DriverMon
  P 05:	1.0.0.0
  P 06:	5a0c2db1
  P 07:	cc
  P 08:	0
  P 09:	System.NullReferenceException
  OS version:	6.1.7601.2.1.0.256.1
 
  next info 1:	0a9e
  next info 2:	0a9e372d3b4ad19135b953a78882e789
  next info 3:	0a9e
  next info 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by zodiacon** [comment]
Currently, I compiled it for x64 only. You'll have to compile from source for x86
