### ISSUE TITLE
[Feature] Use hexdump view to export to file

### ISSUE THREAD

**Issue by hugsy** [zodiacon/DriverMon#4]
Hi,

First of, thanks for the great tool. I've been searching for quite time for a clean driver monitor, and this is exactly what I wanted.

I was wondering if it could be possible to add to the hexdump view a functionality to export to file on disk, so that it could be later analyzed through hexeditors or bindiffers? 
I'm no C# guru but if you accept PRs I'd be happy to do that.

Thanks.

**Comment by zodiacon** [comment]
I accept PRs...
In any case, it's pretty easy to add, so I'll do that tomorrow

**Comment by zodiacon** [comment]
Done!

**Comment by hugsy** [comment]
So cool! Thanks!
I've been using your tool quite intensively since I've discovered it, so I might drop some PRs occasionally. Thank you for making such a great tool open-source!
